version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx-skl
        networks:
            main:
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ../../skl-test:/app/skl-test
            - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
#            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 81:81
            - "443:443"
        depends_on:
            - php
            - postgres
            - redis
#            - centrifugo
    php:
        build: ./php
        restart: always
        container_name: php-skl
        networks:
            main:
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ../../skl-test:/app/skl-test
#    centrifugo:
#        image: centrifugo/centrifugo:latest
#        command: centrifugo -c laravel-centrifugo.json
#        container_name: centrifugo
#        networks:
#            main:
#        ports:
#            - 8000:8000
#        volumes:
#            - "./config/centrifugo:/centrifugo"
#        ulimits:
#            nproc: 65536
#            nofile:
#                soft: 65536
#                hard: 65536
    postgres:
        image: postgres
        container_name: postgres-skl
        networks:
            main:
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis
        container_name: redis-skl
        mem_limit: 1024m
        networks:
            main:
        ports:
            - 6379:6379
        command: ["sh", "-c", "exec redis-server --requirepass \"root\""]
networks:
    main:
        external: True
